// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ObligatorioRazor.Data;

#nullable disable

namespace ObligatorioRazor.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241206011354_nuevouser")]
    partial class nuevouser
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ObligatorioRazor.Model.Habitacion", b =>
                {
                    b.Property<int>("HabitacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HabitacionId"), 1L, 1);

                    b.Property<bool>("EstaDisponible")
                        .HasColumnType("bit");

                    b.Property<int>("Precio")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HabitacionId");

                    b.ToTable("Habitacion");

                    b.HasData(
                        new
                        {
                            HabitacionId = 1,
                            EstaDisponible = false,
                            Precio = 100,
                            Tipo = "Single"
                        },
                        new
                        {
                            HabitacionId = 2,
                            EstaDisponible = false,
                            Precio = 150,
                            Tipo = "Double"
                        },
                        new
                        {
                            HabitacionId = 3,
                            EstaDisponible = false,
                            Precio = 90,
                            Tipo = "Single"
                        },
                        new
                        {
                            HabitacionId = 4,
                            EstaDisponible = false,
                            Precio = 90,
                            Tipo = "Single"
                        },
                        new
                        {
                            HabitacionId = 5,
                            EstaDisponible = false,
                            Precio = 160,
                            Tipo = "Double"
                        },
                        new
                        {
                            HabitacionId = 6,
                            EstaDisponible = false,
                            Precio = 400,
                            Tipo = "Suite Deluxe"
                        },
                        new
                        {
                            HabitacionId = 7,
                            EstaDisponible = false,
                            Precio = 85,
                            Tipo = "Single"
                        },
                        new
                        {
                            HabitacionId = 8,
                            EstaDisponible = false,
                            Precio = 155,
                            Tipo = "Double"
                        },
                        new
                        {
                            HabitacionId = 9,
                            EstaDisponible = false,
                            Precio = 500,
                            Tipo = "Suite Premium"
                        });
                });

            modelBuilder.Entity("ObligatorioRazor.Model.Reserva", b =>
                {
                    b.Property<int>("IDReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ReservaID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDReserva"), 1L, 1);

                    b.Property<string>("EmailCliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EstaPagada")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaReserva")
                        .HasColumnType("datetime2");

                    b.Property<int>("HabitacionId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("IDReserva");

                    b.HasIndex("HabitacionId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Reserva");

                    b.HasData(
                        new
                        {
                            IDReserva = 1,
                            EmailCliente = "juan.perez@gmail.com",
                            EstaPagada = true,
                            FechaFin = new DateTime(2024, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaInicio = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaReserva = new DateTime(2024, 12, 5, 0, 0, 0, 0, DateTimeKind.Local),
                            HabitacionId = 1,
                            UsuarioId = 1
                        },
                        new
                        {
                            IDReserva = 2,
                            EmailCliente = "maria.lopez@gmail.com",
                            EstaPagada = false,
                            FechaFin = new DateTime(2024, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaInicio = new DateTime(2024, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaReserva = new DateTime(2024, 12, 5, 0, 0, 0, 0, DateTimeKind.Local),
                            HabitacionId = 2,
                            UsuarioId = 2
                        },
                        new
                        {
                            IDReserva = 3,
                            EmailCliente = "carlos.rodriguez@gmail.com",
                            EstaPagada = true,
                            FechaFin = new DateTime(2024, 12, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaInicio = new DateTime(2024, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaReserva = new DateTime(2024, 12, 5, 0, 0, 0, 0, DateTimeKind.Local),
                            HabitacionId = 3,
                            UsuarioId = 3
                        },
                        new
                        {
                            IDReserva = 4,
                            EmailCliente = "fernando.bonilla@gmail.com",
                            EstaPagada = true,
                            FechaFin = new DateTime(2024, 12, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaInicio = new DateTime(2024, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaReserva = new DateTime(2024, 12, 5, 0, 0, 0, 0, DateTimeKind.Local),
                            HabitacionId = 4,
                            UsuarioId = 4
                        },
                        new
                        {
                            IDReserva = 5,
                            EmailCliente = "nelson.gonzalez@gmail.com",
                            EstaPagada = false,
                            FechaFin = new DateTime(2024, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaInicio = new DateTime(2024, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaReserva = new DateTime(2024, 12, 5, 0, 0, 0, 0, DateTimeKind.Local),
                            HabitacionId = 5,
                            UsuarioId = 5
                        },
                        new
                        {
                            IDReserva = 6,
                            EmailCliente = "ana.garcia@gmail.com",
                            EstaPagada = true,
                            FechaFin = new DateTime(2024, 12, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaInicio = new DateTime(2024, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaReserva = new DateTime(2024, 12, 5, 0, 0, 0, 0, DateTimeKind.Local),
                            HabitacionId = 6,
                            UsuarioId = 6
                        },
                        new
                        {
                            IDReserva = 7,
                            EmailCliente = "luis.sanchez@gmail.com",
                            EstaPagada = true,
                            FechaFin = new DateTime(2024, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaInicio = new DateTime(2024, 12, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaReserva = new DateTime(2024, 12, 5, 0, 0, 0, 0, DateTimeKind.Local),
                            HabitacionId = 7,
                            UsuarioId = 7
                        },
                        new
                        {
                            IDReserva = 8,
                            EmailCliente = "elena.martinez@gmail.com",
                            EstaPagada = false,
                            FechaFin = new DateTime(2024, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaInicio = new DateTime(2024, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaReserva = new DateTime(2024, 12, 5, 0, 0, 0, 0, DateTimeKind.Local),
                            HabitacionId = 8,
                            UsuarioId = 8
                        },
                        new
                        {
                            IDReserva = 9,
                            EmailCliente = "david.fernandez@gmail.com",
                            EstaPagada = true,
                            FechaFin = new DateTime(2024, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaInicio = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaReserva = new DateTime(2024, 12, 5, 0, 0, 0, 0, DateTimeKind.Local),
                            HabitacionId = 9,
                            UsuarioId = 9
                        },
                        new
                        {
                            IDReserva = 10,
                            EmailCliente = "sofia.gonzalez@gmail.com",
                            EstaPagada = false,
                            FechaFin = new DateTime(2024, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaInicio = new DateTime(2024, 12, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaReserva = new DateTime(2024, 12, 5, 0, 0, 0, 0, DateTimeKind.Local),
                            HabitacionId = 5,
                            UsuarioId = 10
                        });
                });

            modelBuilder.Entity("ObligatorioRazor.Model.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UsuarioID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuario");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Juan Pérez"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "María López"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Carlos Rodriguez"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Fernando Bonilla"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Nelson Gonzalez"
                        },
                        new
                        {
                            Id = 6,
                            Nombre = "Ana García"
                        },
                        new
                        {
                            Id = 7,
                            Nombre = "Luis Sánchez"
                        },
                        new
                        {
                            Id = 8,
                            Nombre = "Elena Martínez"
                        },
                        new
                        {
                            Id = 9,
                            Nombre = "David Fernández"
                        },
                        new
                        {
                            Id = 10,
                            Nombre = "Sofia González"
                        });
                });

            modelBuilder.Entity("ObligatorioRazor.Model.Reserva", b =>
                {
                    b.HasOne("ObligatorioRazor.Model.Habitacion", "Habitacion")
                        .WithMany("Reservas")
                        .HasForeignKey("HabitacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ObligatorioRazor.Model.Usuario", "Usuario")
                        .WithMany("Reservas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Habitacion");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ObligatorioRazor.Model.Habitacion", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("ObligatorioRazor.Model.Usuario", b =>
                {
                    b.Navigation("Reservas");
                });
#pragma warning restore 612, 618
        }
    }
}
